project_id = "jfnjvphxhzxojxgptmtu"

[functions.google-places]
  verify_jwt = false  # Explicitly disable JWT verification for this function

[functions.qr-redirect]
  # verify_jwt = true # Default: JWT verification is enabled. Uncomment and set to 'false' to disable.
