@echo off
set SUPABASE_SERVICE_ROLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impmbmp2cGh4aHp4b2p4Z3B0bXR1Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTczNjcyODIwOSwiZXhwIjoyMDUyMzA0MjA5fQ.gEv5x0uthgFUa6QqLMmACdZBjbe5wPuuQIToeghuU0U

echo 🚀 Importing complete clean reviews to Supabase...
echo.

node import_complete_reviews.cjs

echo.
echo ✅ Complete import finished!
pause
