// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

// Fallbacks for project jfnjvphxhzxojxgptmtu (from Supabase) so the app loads when
// VITE_SUPABASE_URL / VITE_SUPABASE_ANON_KEY are not set at build time (e.g. deployed without env).
const FALLBACK_SUPABASE_URL = 'https://jfnjvphxhzxojxgptmtu.supabase.co';
const FALLBACK_ANON_KEY =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impmbmp2cGh4aHp4b2p4Z3B0bXR1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY3MjgyMDksImV4cCI6MjA1MjMwNDIwOX0.D7fqEZPOOvqVnrtLPwAJ4tqGyTPY8uXjBejgU8Vshd4';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL ?? FALLBACK_SUPABASE_URL;
const SUPABASE_ANON_KEY =
  import.meta.env.VITE_SUPABASE_ANON_KEY ?? FALLBACK_ANON_KEY;

// Import the supabase client like this:
// import { supabase } from "@shared/lib/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
