import type { LucideIcon } from 'lucide-react';
// Import all icons used in the codebase for tree-shaking
import { 
  AlertCircle,
  AlertTriangle,
  ArrowUpRight,
  Bug,
  Building,
  Calculator,
  Calendar,
  CheckCircle,
  ChevronDown,
  ChevronUp,
  Clock,
  Clock3,
  Compass,
  Crown,
  Download,
  ExternalLink,
  FileText,
  Gift,
  Heart,
  Info,
  Loader2,
  LogOut,
  MapPin,
  MessageCircle,
  Minus,
  Navigation,
  Phone,
  PieChart,
  Plus,
  PlusCircle,
  QrCode,
  Quote,
  RefreshCw,
  Scissors,
  Star,
  ToggleRight,
  Trash2,
  TrendingUp,
  Upload,
  User,
  Users,
  X,
  // Additional icons from UI elements
  Sparkles as SparklesIcon,
  ArrowRight,
  Edit2,
  Save,
  Pencil,
  MoreVertical,
  Mail,
  Filter,
  Search,
  ChevronLeft,
  ChevronRight,
  CalendarIcon,
  Building2,
  Briefcase,
  ArrowRightLeft,
  Edit,
  Share2,
  Check,
  Eye,
  DollarSign,
  Settings,
  Home,
} from 'lucide-react';

// Map of icon name to component
const iconMap: Record<string, LucideIcon> = {
  AlertCircle,
  AlertTriangle,
  ArrowUpRight,
  Bug,
  Building,
  Calculator,
  Calendar,
  CheckCircle,
  ChevronDown,
  ChevronUp,
  Clock,
  Clock3,
  Compass,
  Crown,
  Download,
  ExternalLink,
  FileText,
  Gift,
  Heart,
  Info,
  Loader2,
  LogOut,
  MapPin,
  MessageCircle,
  Minus,
  Navigation,
  Phone,
  PieChart,
  Plus,
  PlusCircle,
  QrCode,
  Quote,
  RefreshCw,
  Scissors,
  Sparkles: SparklesIcon,
  Star,
  ToggleRight,
  Trash2,
  TrendingUp,
  Upload,
  User,
  Users,
  X,
  ArrowRight,
  Edit2,
  Save,
  Pencil,
  MoreVertical,
  Mail,
  Filter,
  Search,
  ChevronLeft,
  ChevronRight,
  CalendarIcon,
  Building2,
  Briefcase,
  ArrowRightLeft,
  Edit,
  Share2,
  Check,
  Eye,
  DollarSign,
  Settings,
  Home,
};

// Fallback icon
const FallbackIcon = SparklesIcon;

/**
 * Get icon component by name
 * Returns a LucideIcon component or FallbackIcon if not found
 */
export function getIcon(name: string | null): LucideIcon {
  if (!name) return FallbackIcon;
  
  // Normalize name: remove spaces, ensure first letter uppercase
  const normalized = name.trim().replace(/\s+/g, '');
  const iconName = normalized.charAt(0).toUpperCase() + normalized.slice(1);
  
  return iconMap[iconName] || FallbackIcon;
}