
export const countryToCode: Record<string, string> = {
  "السعودية": "SA",
  "مصر": "EG",
  "الأردن": "JO",
  "سوريا": "SY",
  "لبنان": "LB",
  "فلسطين": "PS",
  "اليمن": "YE",
  "العراق": "IQ",
  "المغرب": "MA",
  "تونس": "TN",
  "الجزائر": "DZ",
  "السودان": "SD",
  "ليبيا": "LY",
  "باكستان": "PK",
  "الهند": "IN",
  "بنغلاديش": "BD",
  "الفلبين": "PH",
  "إندونيسيا": "ID",
  "ماليزيا": "MY",
  "تايلاند": "TH",
  "Saudi Arabia": "SA",
  "Egypt": "EG",
  "Jordan": "JO",
  "Syria": "SY",
  "Lebanon": "LB",
  "Palestine": "PS",
  "Yemen": "YE",
  "Iraq": "IQ",
  "Morocco": "MA",
  "Tunisia": "TN",
  "Algeria": "DZ",
  "Sudan": "SD",
  "Libya": "LY",
  "Pakistan": "PK",
  "India": "IN",
  "Bangladesh": "BD",
  "Philippines": "PH",
  "Indonesia": "ID",
  "Malaysia": "MY",
  "Thailand": "TH",
  "SA": "SA",
  "EG": "EG",
  "JO": "JO",
  "SY": "SY",
  "LB": "LB",
  "PS": "PS",
  "YE": "YE",
  "IQ": "IQ",
  "MA": "MA",
  "TN": "TN",
  "DZ": "DZ",
  "SD": "SD",
  "LY": "LY",
  "PK": "PK",
  "IN": "IN",
  "BD": "BD",
  "PH": "PH",
  "ID": "ID",
  "MY": "MY",
  "TH": "TH"
};

export const codeToCountry: Record<string, string> = {
  "SA": "Saudi Arabia",
  "EG": "Egypt",
  "JO": "Jordan",
  "SY": "Syria",
  "LB": "Lebanon",
  "PS": "Palestine",
  "YE": "Yemen",
  "IQ": "Iraq",
  "MA": "Morocco",
  "TN": "Tunisia",
  "DZ": "Algeria",
  "SD": "Sudan",
  "LY": "Libya",
  "PK": "Pakistan",
  "IN": "India",
  "BD": "Bangladesh",
  "PH": "Philippines",
  "ID": "Indonesia",
  "MY": "Malaysia",
  "TH": "Thailand"
};
